pool:
  vmImage: 'windows-2019'

variables:
  solution: 'HardcodeAnalyzer.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration Release' 

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*.Test/*.csproj'
    arguments: '--configuration $(buildConfiguration) --logger:trx'

- task: PublishTestResults@2
  inputs:
    testRunner: xUnit
    testResultsFiles: '**/*.trx'

- task: DotNetCoreCLI@2
  inputs:
    command: pack
    projects: '**/*.csproj'

- task: PublishBuildArtifacts@1

trigger:
- master

pr: 
- master
