pool:
  vmImage: 'windows-2019'

variables:
  solution: 'HardcodeAnalyzer.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

trigger:
- master
- ci-upgrade

pr: 
- master

steps:
- task: gittools.gitversion.gitversion-task.GitVersion@4
  displayName: GitVersion
  inputs:
    preferBundledVersion: true
    
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: --configuration Release /property:Version=$(AssemblySemVer)

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*.Test/*.csproj'
    arguments: '--configuration $(buildConfiguration) --logger:trx'

- task: PublishTestResults@2
  inputs:
    testRunner: xUnit
    testResultsFiles: '**/*.trx'

- task: DotNetCoreCLI@2
  inputs:
    command: pack
    projects: **/*.csproj -Version $(NuGetVersionV2)

- task: PublishBuildArtifacts@1
